# Generated by Django 4.0.5 on 2022-07-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_doctor_hospital_patient_doctor_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='spacialist',
            new_name='specialist',
        ),
    ]
