# Generated by Django 4.0.5 on 2022-07-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_spacialist_doctor_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('specialist', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('disease', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=30)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.doctor_2')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RenameModel(
            old_name='Hospital',
            new_name='Hospital_2',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='patient_2',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.hospital_2'),
        ),
        migrations.AddField(
            model_name='doctor_2',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.hospital_2'),
        ),
    ]
