# Generated by Django 4.0.5 on 2022-07-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_doctor_2_patient_2_remove_patient_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_2',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.hospital_2'),
        ),
        migrations.AlterField(
            model_name='patient_2',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.doctor_2'),
        ),
        migrations.AlterField(
            model_name='patient_2',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.hospital_2'),
        ),
    ]
