# Generated by Django 4.0.5 on 2022-07-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_studentnew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentnew',
            options={'ordering': ['name']},
        ),
    ]
