# Generated by Django 4.0.5 on 2022-07-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_studentnew2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentnew2',
            table='student_info2',
        ),
    ]
