# Generated by Django 4.0.5 on 2022-07-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='MyPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.person2',),
        ),
    ]
