# Generated by Django 4.0.5 on 2022-07-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_person2_myperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPerson2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.person2',),
        ),
        migrations.CreateModel(
            name='OrederedPerson',
            fields=[
            ],
            options={
                'ordering': ['last_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.person2',),
        ),
    ]
