# Generated by Django 4.0.5 on 2022-07-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_myperson2_orederedperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPerson3',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.person2', models.Model),
        ),
    ]
