# Generated by Django 4.0.5 on 2022-07-05 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_student3'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonLandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(choices=[(datetime.date(1969, 7, 20), 'Apollo 11 (Eagle)'), (datetime.date(1969, 11, 19), 'Apollo 12 (Intrepid)'), (datetime.date(1971, 2, 5), 'Apollo 14 (Antares)'), (datetime.date(1971, 7, 30), 'Apollo 15 (Falcon)'), (datetime.date(1972, 4, 21), 'Apollo 16 (Orion)'), (datetime.date(1972, 12, 11), 'Apollo 17 (Challenger)')])),
            ],
        ),
    ]
