# Generated by Django 4.0.5 on 2022-07-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(db_column='Address', max_length=25, null=True, verbose_name='Address_of_user'),
        ),
    ]
