# Generated by Django 4.0.5 on 2022-07-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='n',
            field=models.BigIntegerField(),
        ),
    ]
