# Generated by Django 4.0.5 on 2022-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_album_artist_song_album_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='media')),
            ],
        ),
    ]
