# Generated by Django 4.0.5 on 2022-07-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_filing3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, unique=True)),
                ('last_name', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'permissions': [('can_deliver_pizzas', 'can diliver pizzas')],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
