# Generated by Django 4.0.5 on 2022-07-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_dog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='date',
            new_name='data',
        ),
    ]
