# Generated by Django 4.0.5 on 2022-07-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0003_topping_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championed_by', to='polls2.pizza')),
                ('pizzas', models.ManyToManyField(related_name='restaurants', to='polls2.pizza')),
            ],
        ),
    ]
