# Generated by Django 4.0.5 on 2022-07-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0004_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='vegetarian',
            field=models.BooleanField(null=True),
        ),
    ]
