# Generated by Django 4.0.5 on 2022-07-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0006_chapter_book2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
            ],
        ),
    ]
