# Generated by Django 4.0.5 on 2022-07-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0009_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
