# Generated by Django 4.0.5 on 2022-07-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0012_remove_user_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
