# Generated by Django 4.0.5 on 2022-07-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], max_length=1)),
                ('qualification', models.CharField(choices=[('gd', 'Graduate'), ('p_gd', 'Post Graduate')], max_length=5)),
                ('passing_year', models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022')])),
                ('number_of_given_interview', models.IntegerField(default=1)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InterviewUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=35)),
                ('status', models.CharField(choices=[('yes', 'Selected'), ('no', 'Regected')], max_length=3)),
                ('interview_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.interviewcandidate')),
            ],
        ),
    ]
