# Generated by Django 4.0.5 on 2022-07-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewcandidate',
            name='phone',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
