# Generated by Django 4.0.5 on 2022-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_interviewcandidate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewcandidate',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
