# Generated by Django 4.0.5 on 2022-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_interviewcandidate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewupdate',
            name='interviewer',
            field=models.CharField(max_length=50),
        ),
    ]
