# Generated by Django 4.0.5 on 2022-07-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_interviewupdate_interviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewcandidate',
            name='profile',
            field=models.CharField(blank=True, choices=[('python', 'Python Developer'), ('react', 'React Developer'), ('HR', 'Human Resource'), ('BDE', 'Business Development Executive')], max_length=6, null=True),
        ),
    ]
