# Generated by Django 4.0.5 on 2022-07-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_interviewcandidate_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewcandidate',
            name='profile',
            field=models.CharField(choices=[('python', 'Python Developer'), ('react', 'React Developer'), ('HR', 'Human Resource'), ('BDE', 'Business Development Executive')], default='python', max_length=6),
        ),
    ]
